/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import ModeloConection.ConexaoBD;
import ModeloDao.DaoLivro;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modeloBeans.BeansLivro;
import modeloBeans.ModeloTabelaLivro;
import javax.swing.JFormattedTextField;

/**
 *
 * @author rodri
 */
public class CadastroLivro extends javax.swing.JFrame {

    BeansLivro mod = new BeansLivro();
    DaoLivro control = new DaoLivro();
    ConexaoBD conex = new ConexaoBD();
    int flag = 0;
    
    public CadastroLivro() {
        initComponents();
        preecherTabelaLivro("select *from livro order by cod_livro");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonNovoLivro = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jFormattedTextFieldTitulo = new javax.swing.JFormattedTextField();
        jFormattedTextFieldISBN = new javax.swing.JFormattedTextField();
        jFormattedTextFieldEdicao = new javax.swing.JFormattedTextField();
        jFormattedTextFieldAno = new javax.swing.JFormattedTextField();
        jFormattedTextFieldArea = new javax.swing.JFormattedTextField();
        jFormattedTextFieldNome = new javax.swing.JFormattedTextField();
        jFormattedTextFieldSobrenome = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jtCOD = new javax.swing.JTextField();
        jLabelID = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLivro = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonNovoLivro.setText("Novo Livro");
        jButtonNovoLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoLivroActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jTextFieldPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisaActionPerformed(evt);
            }
        });

        jButtonPesquisar.setText("Verificar Livro");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabel2.setText("Titulo:");

        jLabel3.setText("ISBN:");

        jLabel5.setText("Edição:");

        jLabel6.setText("Ano:");

        jLabel7.setText("Área:");

        jLabel8.setText("Autor:");

        jFormattedTextFieldTitulo.setEnabled(false);

        jFormattedTextFieldISBN.setEnabled(false);

        jFormattedTextFieldEdicao.setEnabled(false);

        jFormattedTextFieldAno.setEnabled(false);

        jFormattedTextFieldArea.setEnabled(false);
        jFormattedTextFieldArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldAreaActionPerformed(evt);
            }
        });

        jFormattedTextFieldNome.setEnabled(false);

        jFormattedTextFieldSobrenome.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(161, 161, 161)
                                            .addComponent(jLabel2)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonNovoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(156, 156, 156)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel6))
                                            .addComponent(jLabel5))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFormattedTextFieldAno, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jFormattedTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jFormattedTextFieldISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jFormattedTextFieldEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(38, 38, 38)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jFormattedTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jFormattedTextFieldArea, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextFieldSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1009, 1009, 1009)
                                .addComponent(jLabel4)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jFormattedTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonSalvar)
                                .addGap(3, 3, 3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(jFormattedTextFieldArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButtonCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonNovoLivro)
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonPesquisar)
                            .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextFieldISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(jFormattedTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jFormattedTextFieldEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jFormattedTextFieldAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("BD Livros");

        jtCOD.setEnabled(false);
        jtCOD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCODActionPerformed(evt);
            }
        });

        jLabelID.setText("ID");

        jTableLivro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableLivro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableLivroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableLivro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtCOD, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelID)
                        .addComponent(jtCOD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtCODActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCODActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCODActionPerformed

    private void jTableLivroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLivroMouseClicked
        String titulo_livro = ""+ jTableLivro.getValueAt(jTableLivro.getSelectedRow(),1);
        conex.conexao();
        conex.executaSql("select *from livro where titulo_livro = '"+titulo_livro+"'");
        try {
            conex.rs.first();
            jtCOD.setText(String.valueOf(conex.rs.getInt("cod_livro")));

            jFormattedTextFieldTitulo.setText(conex.rs.getString("titulo_livro"));
            jFormattedTextFieldISBN.setText(conex.rs.getString("isbn_livro"));
            jFormattedTextFieldEdicao.setText(conex.rs.getString("edicao_livro"));
            jFormattedTextFieldAno.setText(conex.rs.getString("ano_livro"));
            jFormattedTextFieldArea.setText(conex.rs.getString("area_livro"));
            jFormattedTextFieldNome.setText(conex.rs.getString("nome_livro"));
            jFormattedTextFieldSobrenome.setText(conex.rs.getString("sobrenome_livro"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "erro ao selecionar dados"+ex);
        }
        conex.desconecta();
      //  jButtonEditar.setEnabled(true);
     //   jButtonExcluir.setEnabled(true);
    }//GEN-LAST:event_jTableLivroMouseClicked

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed

        jFormattedTextFieldTitulo.setEnabled(!true);
        jFormattedTextFieldISBN.setEnabled(!true);
        jFormattedTextFieldEdicao.setEnabled(!true);
        jFormattedTextFieldAno.setEnabled(!true);
        jFormattedTextFieldArea.setEnabled(!true);
        jFormattedTextFieldNome.setEnabled(!true);
        jFormattedTextFieldSobrenome.setEnabled(!true);
        jButtonSalvar.setEnabled(!true);
        jButtonCancelar.setEnabled(!true);
        jButtonNovoLivro.setEnabled(true);
//        jButtonEditar.setEnabled(false);
//        jButtonExcluir.setEnabled(false);

        jFormattedTextFieldTitulo.setText("");
        jFormattedTextFieldISBN.setText("");
        jFormattedTextFieldEdicao.setText("");
        jFormattedTextFieldArea.setText("");
        jFormattedTextFieldAno.setText("");
        jFormattedTextFieldNome.setText("");
        jFormattedTextFieldSobrenome.setText("");
        jTextFieldPesquisa.setText("");
        jTextFieldPesquisa.setText("");
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        mod.setPesquisa (jTextFieldPesquisa.getText());
        BeansLivro model = control.buscaLivro(mod);

        jtCOD.setText(String.valueOf(model.getCodigo()));

        jFormattedTextFieldTitulo.setText(model.getTitulo());
        jFormattedTextFieldISBN.setText(model.getISBN());
        jFormattedTextFieldEdicao.setText(model.getEdicao());
        jFormattedTextFieldAno.setText(String.valueOf(model.getAno()));
        jFormattedTextFieldArea.setText(model.getArea());
        jFormattedTextFieldNome.setText(model.getNome());
        jFormattedTextFieldSobrenome.setText(model.getSobrenome());
        // jButtonEditar.setEnabled(true);
        //jButtonExcluir.setEnabled(true);
        jtCOD.setText("");
        jFormattedTextFieldTitulo.setText("");
        jFormattedTextFieldISBN.setText("");
        jFormattedTextFieldEdicao.setText("");
        jFormattedTextFieldArea.setText("");
        jFormattedTextFieldAno.setText("");
        jFormattedTextFieldNome.setText("");
        jFormattedTextFieldSobrenome.setText("");
        jTextFieldPesquisa.setText("");
        jTextFieldPesquisa.setText("");
        preecherTabelaLivro(("select *from livro where titulo_livro like'%"+mod.getPesquisa()+"%'"));
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jTextFieldPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisaActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if(jFormattedTextFieldNome.getText().isEmpty()){
            JOptionPane.showConfirmDialog(null, "campo nome vazio");
            jFormattedTextFieldNome.requestFocus();
        }else if(jFormattedTextFieldSobrenome.getText().isEmpty()){
            JOptionPane.showConfirmDialog(null, "campo  matricula vazio");
            jFormattedTextFieldSobrenome.requestFocus();
        }else

        if (flag == 1){
            mod.setTitulo(jFormattedTextFieldTitulo.getText());
            mod.setISBN(jFormattedTextFieldISBN.getText());
            mod.setEdicao(jFormattedTextFieldEdicao.getText());
            mod.setAno(Integer.parseInt(jFormattedTextFieldAno.getText()));
            mod.setArea(jFormattedTextFieldArea.getText());
            mod.setNome(jFormattedTextFieldNome.getText());
            mod.setSobrenome(jFormattedTextFieldSobrenome.getText());

            control.Salvar(mod);
            jtCOD.setText("");
            jFormattedTextFieldTitulo.setText("");
            jFormattedTextFieldISBN.setText("");
            jFormattedTextFieldEdicao.setText("");
            jFormattedTextFieldArea.setText("");
            jFormattedTextFieldAno.setText("");
            jFormattedTextFieldNome.setText("");
            jFormattedTextFieldSobrenome.setText("");

            jFormattedTextFieldTitulo.setEnabled(false);
            jFormattedTextFieldISBN.setEnabled(false);
            jFormattedTextFieldEdicao.setEnabled(false);
            jFormattedTextFieldAno.setEnabled(false);
            jFormattedTextFieldArea.setEnabled(false);
            jFormattedTextFieldNome.setEnabled(false);
            jFormattedTextFieldSobrenome.setEnabled(false);

            jButtonSalvar.setEnabled(false);
            jButtonCancelar.setEnabled(false);
            preecherTabelaLivro("select *from livro order by cod_livro");

        }else{

            mod.setCodigo((Integer.parseInt(jtCOD.getText())));
            mod.setTitulo(jFormattedTextFieldTitulo.getText());
            mod.setISBN(jFormattedTextFieldISBN.getText());
            mod.setEdicao(jFormattedTextFieldEdicao.getText());
            mod.setAno(Integer.parseInt(jFormattedTextFieldAno.getText()));
            mod.setNome(jFormattedTextFieldNome.getText());
            mod.setArea(jFormattedTextFieldArea.getText());
            mod.setSobrenome(jFormattedTextFieldSobrenome.getText());
            control.Editar(mod);
            jtCOD.setText("");
            jFormattedTextFieldTitulo.setText("");
            jFormattedTextFieldISBN.setText("");
            jFormattedTextFieldEdicao.setText("");
            jFormattedTextFieldArea.setText("");
            jFormattedTextFieldAno.setText("");
            jFormattedTextFieldNome.setText("");
            jFormattedTextFieldSobrenome.setText("");

            jFormattedTextFieldTitulo.setEnabled(false);
            jFormattedTextFieldISBN.setEnabled(false);
            jFormattedTextFieldEdicao.setEnabled(false);
            jFormattedTextFieldAno.setEnabled(false);
            jFormattedTextFieldArea.setEnabled(false);
            jFormattedTextFieldNome.setEnabled(false);
            jFormattedTextFieldSobrenome.setEnabled(false);

            jButtonSalvar.setEnabled(false);
            jButtonCancelar.setEnabled(false);
            jButtonNovoLivro.setEnabled(true);
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonNovoLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoLivroActionPerformed
        flag = 1;

        jFormattedTextFieldTitulo.setEnabled(true);
        jFormattedTextFieldISBN.setEnabled(true);
        jFormattedTextFieldEdicao.setEnabled(true);
        jFormattedTextFieldAno.setEnabled(true);
        jFormattedTextFieldArea.setEnabled(true);
        jFormattedTextFieldNome.setEnabled(true);
        jFormattedTextFieldSobrenome.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);

        jFormattedTextFieldTitulo.setText("");
        jFormattedTextFieldISBN.setText("");
        jFormattedTextFieldEdicao.setText("");
        jFormattedTextFieldArea.setText("");
        jFormattedTextFieldAno.setText("");
        jFormattedTextFieldNome.setText("");
        jFormattedTextFieldSobrenome.setText("");

        jTextFieldPesquisa.setText("");

      //  jButtonExcluir.setEnabled(false);
     //   jButtonEditar.setEnabled(false);
        jButtonPesquisar.setEnabled(true);
        jTextFieldPesquisa.setEnabled(true);
        jtCOD.setText("");
    }//GEN-LAST:event_jButtonNovoLivroActionPerformed

    private void jFormattedTextFieldAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldAreaActionPerformed

    /**
     * @param args the command line arguments
     */
    
     public void preecherTabelaLivro(String Sql){
        ArrayList dados = new ArrayList();
        String [] colunas = new String[]{"ID","Titulo","ISBN","Edição","Ano","Área","Nome","Sobrenome"};
        conex.conexao();
        conex.executaSql(Sql);

        try {
            conex.rs.first();
            do{
                dados.add(new Object[] {conex.rs.getInt("cod_livro"),conex.rs.getString("titulo_livro"),conex.rs.getString("isbn_livro"),conex.rs.getString("edicao_livro"), conex.rs.getInt("ano_livro"), conex.rs.getString("area_livro"),conex.rs.getString("nome_livro"), conex.rs.getString("sobrenome_livro")});
            }while(conex.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Não há nenhum dado disponível, por favor insira");
        }
        ModeloTabelaLivro modelo = new ModeloTabelaLivro(dados,colunas);
        jTableLivro.setModel(modelo);
        jTableLivro.getColumnModel().getColumn(0).setPreferredWidth(25);
        jTableLivro.getColumnModel().getColumn(0).setResizable(false);
        jTableLivro.getColumnModel().getColumn(1).setPreferredWidth(90); 
        jTableLivro.getColumnModel().getColumn(1).setResizable(false);
        jTableLivro.getColumnModel().getColumn(2).setPreferredWidth(90); 
        jTableLivro.getColumnModel().getColumn(2).setResizable(false);
        jTableLivro.getColumnModel().getColumn(3).setPreferredWidth(90); 
        jTableLivro.getColumnModel().getColumn(3).setResizable(false);
        jTableLivro.getColumnModel().getColumn(4).setPreferredWidth(90);
        jTableLivro.getColumnModel().getColumn(4).setResizable(false);
        jTableLivro.getColumnModel().getColumn(5).setPreferredWidth(90);
        jTableLivro.getColumnModel().getColumn(5).setResizable(false);
        jTableLivro.getColumnModel().getColumn(6).setPreferredWidth(90);
        jTableLivro.getColumnModel().getColumn(6).setResizable(false);
        jTableLivro.getColumnModel().getColumn(7).setPreferredWidth(90);
        jTableLivro.getColumnModel().getColumn(7).setResizable(false);

        
        jTableLivro.getTableHeader().setReorderingAllowed(false);
        jTableLivro.setAutoResizeMode(jTableLivro.AUTO_RESIZE_OFF);
        jTableLivro.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conex.desconecta();
     }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroLivro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonNovoLivro;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JFormattedTextField jFormattedTextFieldAno;
    private javax.swing.JFormattedTextField jFormattedTextFieldArea;
    private javax.swing.JFormattedTextField jFormattedTextFieldEdicao;
    private javax.swing.JFormattedTextField jFormattedTextFieldISBN;
    private javax.swing.JFormattedTextField jFormattedTextFieldNome;
    private javax.swing.JFormattedTextField jFormattedTextFieldSobrenome;
    private javax.swing.JFormattedTextField jFormattedTextFieldTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLivro;
    private javax.swing.JTextField jTextFieldPesquisa;
    private javax.swing.JTextField jtCOD;
    // End of variables declaration//GEN-END:variables
}
